<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4DTVSHD" failures="1" tests="5" name="interviewquestions.SeleniumInterviewQuestionsReturnFailedTestCase" time="0.080" errors="0" timestamp="2024-04-09T02:18:58 IST" skipped="4">
  <testcase classname="interviewquestions.SeleniumInterviewQuestionsReturnFailedTestCase" name="testcase1" time="0.007">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="interviewquestions.SeleniumInterviewQuestionsReturnFailedTestCase" name="testcase1" time="0.038">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="interviewquestions.SeleniumInterviewQuestionsReturnFailedTestCase" name="testcase1" time="0.015">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at interviewquestions.SeleniumInterviewQuestionsReturnFailedTestCase.testcase1(SeleniumInterviewQuestionsReturnFailedTestCase.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="interviewquestions.SeleniumInterviewQuestionsReturnFailedTestCase" name="testcase1" time="0.008">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="interviewquestions.SeleniumInterviewQuestionsReturnFailedTestCase" name="testcase1" time="0.012">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
</testsuite> <!-- interviewquestions.SeleniumInterviewQuestionsReturnFailedTestCase -->
